ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      DOUBLE PRECISION G
      COMMON/STRONG/ G

      DOUBLE COMPLEX GAL(2)
      COMMON/WEAK/ GAL

      DOUBLE PRECISION MU_R
      COMMON/RSCALE/ MU_R

      DOUBLE PRECISION NF
      PARAMETER(NF=4)

      DOUBLE PRECISION MDL_MSS1,MDL_MT,MDL_MW,MDL_MSS2,MDL_MZ,MDL_MTA
     $ ,MDL_MB,MDL_MH

      COMMON/MASSES/ MDL_MSS1,MDL_MT,MDL_MW,MDL_MSS2,MDL_MZ,MDL_MTA
     $ ,MDL_MB,MDL_MH


      DOUBLE PRECISION MDL_WW,MDL_WT,MDL_WZ,MDL_WSS2,MDL_WSS1,MDL_WH

      COMMON/WIDTHS/ MDL_WW,MDL_WT,MDL_WZ,MDL_WSS2,MDL_WSS1,MDL_WH


      DOUBLE COMPLEX GC_8, GC_11, GC_12, GC_13

      COMMON/COUPLINGS/ GC_8, GC_11, GC_12, GC_13

